### ISSUE TITLE
Module not found in the opentofu registry

### ISSUE THREAD

**Issue by anthonyangel** [J0hn-B/terraform-port-blueprint#6]
Hi, thanks for making this module. If you're using opentofu rather than Terraform you get the following error as this module isn't present in the opentofu registry.

```
Initializing modules...
╷
│ Error: Module not found
│ 
│   on main.tf line 14:
│   14: module "port" {
│ 
│ Module J0hn-B/blueprint/port ("port" from main.tf:14) cannot be found in
│ the module registry at registry.opentofu.org.
│ 
│ If you believe this module is missing from the registry, please submit a
│ issue on the OpenTofu Registry https://github.com/opentofu/registry/issues/
```

I worked around this by swapping the module source to be github rather than a Terraform registry, i.e.
```
module "port" {
  source  = "github.com/J0hn-B/terraform-port-blueprint?ref=v0.1.1"
}
```

**Comment by J0hn-B** [comment]
Hello @anthonyangel

Glad you found the module useful and thank you for the feedback.
I can verify your solution of swapping to GitHub as source works fine.

I added a note to the README.md file to help others who may encounter the same issue.

![image](https://github.com/J0hn-B/terraform-port-blueprint/assets/40946247/af1dcdc6-5811-415c-babf-593a827323bf)
